// hidden line generated by Node.js
// var exports = module.exports = {};

var KhachHang = require('./model');
var _ = require('lodash');
var controller = {};

controller.params = function(req, res, next, id) {
    // use the id to find object from DB and attach to req
    KhachHang
        .findById(id)
        .then(
            function(item){
                if(!item){
                    next(new Error('No KhachHang with id ' + id));
                }else{
                    req.khachhang = item;
                    next();
                }
            }, 
            function(err){
                next(err);
            }
        );
};

controller.get = function(req, res, next) {
    KhachHang
        .find({})
        .then(
            function(items){
                res.header("X-Total-Count", items.length);
                res.json(items);
            }, 
            function(err){
                next(err);
            }
        );
};

controller.getOne = function(req, res, next) {
    var khachhang = req.khachhang;
    res.json(khachhang);
};

controller.put = function(req, res, next) {
    var curKhachHang = req.khachhang;
    var newKhachHang = req.body;

    _.merge(curKhachHang, newKhachHang);

    curKhachHang.save(function(err, item){
        if(err){
            next(err);
        }else{
            res.json(item);
        }
    });
};

controller.post = function(req, res, next) {
    var newKhachHang = req.body;
    KhachHang
        .create(newKhachHang)
        .then(
            function(item){
                res.json(item);
            }, 
            function(err){
                next(err);
            }
        );
};

controller.delete = function(req, res, next) {
    var KhachHang = req.khachhang;
    KhachHang.remove(function(err, item){
        if(err){
            next(err);
        }else{
            res.json(item);
        }
    });
};

module.exports = controller;